# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tobiagasparonidemo
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: feature-flag-service
# "service" is the name of this project. This will also be added to your AWS resource names.
service: feature-flags-service

stages:
  default:
    params:
      tableName: "feature-flags-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [FeatureFlagsTable, Arn]
  environment:
    FEATURE_FLAGS_TABLE: ${param:tableName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    FeatureFlagsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: featureFlagId
            AttributeType: S
        KeySchema:
          - AttributeName: featureFlagId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
