org: tobiagasparonidemo
app: feature-flags-service
service: feature-flags-service

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: FeatureFlags  # replace with your table name

  # Move iamRoleStatements here under provider
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

# Define resources, including DynamoDB table
resources:
  Resources:
    MyDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

functions:
  createItem:
    handler: handler.createItem
    events:
      - http:
          path: items
          method: post
          cors: true

  getItem:
    handler: handler.getItem
    events:
      - http:
          path: items/{id}
          method: get
          cors: true

  updateItem:
    handler: handler.updateItem
    events:
      - http:
          path: items/{id}
          method: put
          cors: true

  deleteItem:
    handler: handler.deleteItem
    events:
      - http:
          path: items/{id}
          method: delete
          cors: true
