org: tobiagasparonidemo
app: feature-flags
service: flag-management

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'stg'}  # Defaults to 'stg' if no stage is specified
  environment:
    FEATURE_FLAGS_TABLE: ${self:custom.tableName.${self:provider.stage}}

  # Move iamRoleStatements here under provider
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FEATURE_FLAGS_TABLE}"

plugins:
  - serverless-esbuild

custom:
  tableName:
    stg: "feature-flags-table-stg"
    prd: "feature-flags-table-prd"
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: "node20"
    outdir: "dist"

# Define resources, including DynamoDB table
resources:
  Resources:
    MyDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.FEATURE_FLAGS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

functions:
  createFeatureFlag:
    handler: dist/index.createFeatureFlag
    package:
      individually: true
    events:
      - http:
          path: featureFlags
          method: post
          cors: true

  getFeatureFlag:
    handler: dist/index.getFeatureFlag
    package:
      individually: true
    events:
      - http:
          path: featureFlags/{id}
          method: get
          cors: true

  listFeatureFlags:
    handler: dist/index.listFeatureFlags
    package:
      individually: true
    events:
      - http:
          path: featureFlags
          method: get
          cors: true

  updateFeatureFlag:
    handler: dist/index.updateFeatureFlag
    package:
      individually: true
    events:
      - http:
          path: featureFlags/{id}
          method: put
          cors: true

  deleteFeatureFlag:
    handler: dist/index.deleteFeatureFlag
    package:
      individually: true
    events:
      - http:
          path: featureFlags/{id}
          method: delete
          cors: true
